version: "3"
services:
  ecommerce-mysql:
    platform: linux/x86_64
    restart: always
    image: mysql:5.7
    container_name: ecommerce-mysql
    ports:
      - "3366:3306"
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - TZ=Asia/Seoul
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password --skip-grant-tables --init-file /data/application/init.sql
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
