spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3366/ecommerce
    username: admin
    password: password
    testQuery: "SELECT 1"
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create
