server:
  port: 0 # random port

spring:
  application:
    name: product-service-app
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
        jdbc:
          batch_size: 100
          order_inserts: true
#  kafka:
#    consumer:
#      group-id: consumerGroupId
#      key-deserializer: StringDeserializer.class
#      value-deserializer: StringDeserializer.class
#    bootstrap-servers: 127.0.0.1:9092

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
